replicaCount: 1
image:
  repository: 192.168.49.1:7000/tvbot  # <-- Изменено
  tag: "latest"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
containerPort: 8000
ingress:
  enabled: true
  host: tvbot.local
